services:
  thinkarr:
    image: chrisrothwell/thinkarr:latest
    container_name: thinkarr
    environment:
      - PUID=1000 #CHANGE_TO_YOUR_UID
      - PGID=1000 #CHANGE_TO_YOUR_GID
      - TZ=UTC #CHANGE_TO_YOUR_TZ
      #- SECURE_COOKIES=true # Uncomment if running behind a reverse proxy (HTTPS)
    volumes:
      - ./config:/config
    ports:
      - 3000:3000/tcp
    #network_mode: plexbridge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
